language: csharp
solution: HoneybeeDotNet.sln
mono: latest

install:
  - nuget restore HoneybeeDotNet.sln
  - nuget install NUnit.ConsoleRunner -Version 3.10.0 -OutputDirectory packages
  - msbuild /p:Configuration=Release HoneybeeDotNet.sln
  - export BUILD_VERSION=$(monodis --assembly src/HoneybeeDotNet/bin/Release/HoneybeeDotNet.dll | grep -Po '([0-9]{1,}\.)+[0-9]{1,}')

script:
  - rm -f src/HoneybeeDotNet.Test/bin/Debug/HoneybeeDotNet.Test.dll
  - mono ./packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe src/HoneybeeDotNet.Test/bin/Release/HoneybeeDotNet.Test.dll
  

deploy:
  provider: script
  skip_cleanup: true
  script:
    - /bin/sh ./deploy.sh
  on:
    branch: master