
stages:
  - version
  - test_Publish
jobs:
  include:
    - stage: version
      script: 
        - echo "Do SemanticVersioning......................."

    - stage: test_Publish
      sudo: required
      language: csharp
      solution: HoneybeeDotNet.sln
      mono: latest
      install:
        - nuget restore HoneybeeDotNet.sln
        - nuget install NUnit.ConsoleRunner -Version 3.10.0 -OutputDirectory packages
        - xbuild /p:Configuration=Release HoneybeeDotNet.sln
      script:
        - rm -f src/HoneybeeDotNet.Test/bin/Debug/HoneybeeDotNet.Test.dll
        - mono ./packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe src/HoneybeeDotNet.Test/bin/Release/HoneybeeDotNet.Test.dll
        - cd src/HoneybeeDotNet/
        - nuget pack src/HoneybeeDotNet/HoneybeeDotNet.csproj -Build -Version 1.14.1
        - sleep 5
        - nuget push *.nupkg -ApiKey $ApiKey -Source $NUGET_SOURCE