language: csharp
solution: HoneybeeSchema.sln
mono: latest

install:
  - nuget restore HoneybeeSchema.sln
  - nuget install NUnit.ConsoleRunner -Version 3.10.0 -OutputDirectory packages
  - msbuild /p:Configuration=Release HoneybeeSchema.sln
  - export BUILD_VERSION=$(monodis --assembly src/HoneybeeSchema/bin/Release/HoneybeeSchema.dll | grep -Po '([0-9]{1,}\.)+[0-9]{1,}')

script:
  - rm -f src/HoneybeeSchema.Test/bin/Debug/HoneybeeSchema.Test.dll
  - mono ./packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe src/HoneybeeSchema.Test/bin/Release/HoneybeeSchema.Test.dll
  

deploy:
  provider: script
  skip_cleanup: true
  script:
    - /bin/sh ./deploy.sh
  on:
    branch: master