
stages:
  - test_Publish
jobs:
  include:
    - stage: test_Publish
      sudo: required
      language: csharp
      solution: HoneybeeDotNet.sln
      mono: latest
      install:
        - nuget restore HoneybeeDotNet.sln
        - nuget install NUnit.ConsoleRunner -Version 3.10.0 -OutputDirectory packages
        - msbuild /p:Configuration=Release HoneybeeDotNet.sln
      script:
        - rm -f src/HoneybeeDotNet.Test/bin/Debug/HoneybeeDotNet.Test.dll
        - mono ./packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe src/HoneybeeDotNet.Test/bin/Release/HoneybeeDotNet.Test.dll
        - nuget pack src/HoneybeeDotNet/HoneybeeDotNet.csproj -Build
        - nuget push *.nupkg -ApiKey $NUGET_API_KEY -Source $NUGET_SOURCE
