//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace HoneybeeSchema.Energy
{
	public partial interface IMaterial {}
}

//Classes implemented this interface:
namespace HoneybeeSchema
{
	public partial class EnergyMaterial: HoneybeeSchema.Energy.IMaterial {}
	public partial class EnergyMaterialNoMass: HoneybeeSchema.Energy.IMaterial {}
	public partial class EnergyMaterialVegetation: HoneybeeSchema.Energy.IMaterial {}
	public partial class EnergyWindowMaterialBlind: HoneybeeSchema.Energy.IMaterial {}
	public partial class EnergyWindowMaterialGas: HoneybeeSchema.Energy.IMaterial {}
	public partial class EnergyWindowMaterialGasCustom: HoneybeeSchema.Energy.IMaterial {}
	public partial class EnergyWindowMaterialGasMixture: HoneybeeSchema.Energy.IMaterial {}
	public partial class EnergyWindowMaterialGlazing: HoneybeeSchema.Energy.IMaterial {}
	public partial class EnergyWindowMaterialShade: HoneybeeSchema.Energy.IMaterial {}
	public partial class EnergyWindowMaterialSimpleGlazSys: HoneybeeSchema.Energy.IMaterial {}
}
