/* 
 * Honeybee Model Schema
 *
 * This is the documentation for Honeybee model schema.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HoneybeeDotNet.Api;
using HoneybeeDotNet.Model;
using HoneybeeDotNet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HoneybeeDotNet.Test
{
    /// <summary>
    ///  Class for testing RoofCeilingSetAbridged
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RoofCeilingSetAbridgedTests
    {
        // TODO uncomment below to declare an instance variable for RoofCeilingSetAbridged
        //private RoofCeilingSetAbridged instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RoofCeilingSetAbridged
            //instance = new RoofCeilingSetAbridged();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RoofCeilingSetAbridged
        /// </summary>
        [Test]
        public void RoofCeilingSetAbridgedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RoofCeilingSetAbridged
            //Assert.IsInstanceOf(typeof(RoofCeilingSetAbridged), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'InteriorConstruction'
        /// </summary>
        [Test]
        public void InteriorConstructionTest()
        {
            // TODO unit test for the property 'InteriorConstruction'
        }
        /// <summary>
        /// Test the property 'ExteriorConstruction'
        /// </summary>
        [Test]
        public void ExteriorConstructionTest()
        {
            // TODO unit test for the property 'ExteriorConstruction'
        }
        /// <summary>
        /// Test the property 'GroundConstruction'
        /// </summary>
        [Test]
        public void GroundConstructionTest()
        {
            // TODO unit test for the property 'GroundConstruction'
        }

    }

}
