/* 
 * Honeybee Model Schema
 *
 * This is the documentation for Honeybee model schema.
 *
 * The version of the OpenAPI document: 1.13.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HoneybeeDotNet;

using System.Reflection;
using Newtonsoft.Json;

namespace HoneybeeDotNet.Test
{
    /// <summary>
    ///  Class for testing ScheduleDay
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduleDayTests
    {
        // TODO uncomment below to declare an instance variable for ScheduleDay
        //private ScheduleDay instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScheduleDay
            //instance = new ScheduleDay();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScheduleDay
        /// </summary>
        [Test]
        public void ScheduleDayInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ScheduleDay
            //Assert.IsInstanceOf(typeof(ScheduleDay), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Test]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Times'
        /// </summary>
        [Test]
        public void TimesTest()
        {
            // TODO unit test for the property 'Times'
        }
        /// <summary>
        /// Test the property 'Interpolate'
        /// </summary>
        [Test]
        public void InterpolateTest()
        {
            // TODO unit test for the property 'Interpolate'
        }

    }

}
