//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace HoneybeeSchema
{
	public partial interface IBc {}
}

//Classes implemented this interface:
namespace HoneybeeSchema
{
	public partial class Surface: HoneybeeSchema.IBc {}
	public partial class Outdoors: HoneybeeSchema.IBc {}
	public partial class Ground: HoneybeeSchema.IBc {}
	public partial class Adiabatic: HoneybeeSchema.IBc {}
}
