/* 
 * Honeybee Energy Simulation Parameter Schema
 *
 * This is the documentation for Honeybee energy simulation parameter schema.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HoneybeeSchema;

using System.Reflection;
using Newtonsoft.Json;

namespace HoneybeeSchema.Test
{
    /// <summary>
    ///  Class for testing ASHRAEClearSkyAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ASHRAEClearSkyAllOfTests
    {
        // TODO uncomment below to declare an instance variable for ASHRAEClearSkyAllOf
        //private ASHRAEClearSkyAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ASHRAEClearSkyAllOf
            //instance = new ASHRAEClearSkyAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ASHRAEClearSkyAllOf
        /// </summary>
        [Test]
        public void ASHRAEClearSkyAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ASHRAEClearSkyAllOf
            //Assert.IsInstanceOf(typeof(ASHRAEClearSkyAllOf), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Clearness'
        /// </summary>
        [Test]
        public void ClearnessTest()
        {
            // TODO unit test for the property 'Clearness'
        }

    }

}
