/* 
 * Honeybee Model Schema
 *
 * This is the documentation for Honeybee model schema.
 *
 * The version of the OpenAPI document: 1.36.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HoneybeeSchema;

using System.Reflection;
using Newtonsoft.Json;

namespace HoneybeeSchema.Test
{
    /// <summary>
    ///  Class for testing BaseboardEquipmentType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BaseboardEquipmentTypeTests
    {
        // TODO uncomment below to declare an instance variable for BaseboardEquipmentType
        //private BaseboardEquipmentType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BaseboardEquipmentType
            //instance = new BaseboardEquipmentType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BaseboardEquipmentType
        /// </summary>
        [Test]
        public void BaseboardEquipmentTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" BaseboardEquipmentType
            //Assert.IsInstanceOf(typeof(BaseboardEquipmentType), instance);
        }



    }

}
