/* 
 * Honeybee Model Schema
 *
 * This is the documentation for Honeybee model schema.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HoneybeeSchema;

using System.Reflection;
using Newtonsoft.Json;

namespace HoneybeeSchema.Test
{
    /// <summary>
    ///  Class for testing ConstructionSet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConstructionSetTests
    {
        // TODO uncomment below to declare an instance variable for ConstructionSet
        //private ConstructionSet instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConstructionSet
            //instance = new ConstructionSet();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConstructionSet
        /// </summary>
        [Test]
        public void ConstructionSetInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ConstructionSet
            //Assert.IsInstanceOf(typeof(ConstructionSet), instance);
        }


        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Test]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }
        /// <summary>
        /// Test the property 'Materials'
        /// </summary>
        [Test]
        public void MaterialsTest()
        {
            // TODO unit test for the property 'Materials'
        }
        /// <summary>
        /// Test the property 'Constructions'
        /// </summary>
        [Test]
        public void ConstructionsTest()
        {
            // TODO unit test for the property 'Constructions'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'WallSet'
        /// </summary>
        [Test]
        public void WallSetTest()
        {
            // TODO unit test for the property 'WallSet'
        }
        /// <summary>
        /// Test the property 'FloorSet'
        /// </summary>
        [Test]
        public void FloorSetTest()
        {
            // TODO unit test for the property 'FloorSet'
        }
        /// <summary>
        /// Test the property 'RoofCeilingSet'
        /// </summary>
        [Test]
        public void RoofCeilingSetTest()
        {
            // TODO unit test for the property 'RoofCeilingSet'
        }
        /// <summary>
        /// Test the property 'ApertureSet'
        /// </summary>
        [Test]
        public void ApertureSetTest()
        {
            // TODO unit test for the property 'ApertureSet'
        }
        /// <summary>
        /// Test the property 'DoorSet'
        /// </summary>
        [Test]
        public void DoorSetTest()
        {
            // TODO unit test for the property 'DoorSet'
        }
        /// <summary>
        /// Test the property 'ShadeConstruction'
        /// </summary>
        [Test]
        public void ShadeConstructionTest()
        {
            // TODO unit test for the property 'ShadeConstruction'
        }
        /// <summary>
        /// Test the property 'AirBoundaryConstruction'
        /// </summary>
        [Test]
        public void AirBoundaryConstructionTest()
        {
            // TODO unit test for the property 'AirBoundaryConstruction'
        }

    }

}
