/* 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HoneybeeSchema;

using System.Reflection;
using Newtonsoft.Json;

namespace HoneybeeSchema.Test
{
    /// <summary>
    ///  Class for testing ElectricEquipmentAbridgedAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ElectricEquipmentAbridgedAllOfTests
    {
        // TODO uncomment below to declare an instance variable for ElectricEquipmentAbridgedAllOf
        //private ElectricEquipmentAbridgedAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ElectricEquipmentAbridgedAllOf
            //instance = new ElectricEquipmentAbridgedAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ElectricEquipmentAbridgedAllOf
        /// </summary>
        [Test]
        public void ElectricEquipmentAbridgedAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ElectricEquipmentAbridgedAllOf
            //Assert.IsInstanceOf(typeof(ElectricEquipmentAbridgedAllOf), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
