/* 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HoneybeeSchema;

using System.Reflection;
using Newtonsoft.Json;

namespace HoneybeeSchema.Test
{
    /// <summary>
    ///  Class for testing ModelAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModelAllOfTests
    {
        // TODO uncomment below to declare an instance variable for ModelAllOf
        //private ModelAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelAllOf
            //instance = new ModelAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelAllOf
        /// </summary>
        [Test]
        public void ModelAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ModelAllOf
            //Assert.IsInstanceOf(typeof(ModelAllOf), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Rooms'
        /// </summary>
        [Test]
        public void RoomsTest()
        {
            // TODO unit test for the property 'Rooms'
        }
        /// <summary>
        /// Test the property 'OrphanedFaces'
        /// </summary>
        [Test]
        public void OrphanedFacesTest()
        {
            // TODO unit test for the property 'OrphanedFaces'
        }
        /// <summary>
        /// Test the property 'OrphanedShades'
        /// </summary>
        [Test]
        public void OrphanedShadesTest()
        {
            // TODO unit test for the property 'OrphanedShades'
        }
        /// <summary>
        /// Test the property 'OrphanedApertures'
        /// </summary>
        [Test]
        public void OrphanedAperturesTest()
        {
            // TODO unit test for the property 'OrphanedApertures'
        }
        /// <summary>
        /// Test the property 'OrphanedDoors'
        /// </summary>
        [Test]
        public void OrphanedDoorsTest()
        {
            // TODO unit test for the property 'OrphanedDoors'
        }
        /// <summary>
        /// Test the property 'NorthAngle'
        /// </summary>
        [Test]
        public void NorthAngleTest()
        {
            // TODO unit test for the property 'NorthAngle'
        }
        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Test]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }
        /// <summary>
        /// Test the property 'Tolerance'
        /// </summary>
        [Test]
        public void ToleranceTest()
        {
            // TODO unit test for the property 'Tolerance'
        }
        /// <summary>
        /// Test the property 'AngleTolerance'
        /// </summary>
        [Test]
        public void AngleToleranceTest()
        {
            // TODO unit test for the property 'AngleTolerance'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

    }

}
