/* 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HoneybeeSchema;

using System.Reflection;
using Newtonsoft.Json;

namespace HoneybeeSchema.Test
{
    /// <summary>
    ///  Class for testing ScheduleRulesetAbridgedAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduleRulesetAbridgedAllOfTests
    {
        // TODO uncomment below to declare an instance variable for ScheduleRulesetAbridgedAllOf
        //private ScheduleRulesetAbridgedAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScheduleRulesetAbridgedAllOf
            //instance = new ScheduleRulesetAbridgedAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScheduleRulesetAbridgedAllOf
        /// </summary>
        [Test]
        public void ScheduleRulesetAbridgedAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ScheduleRulesetAbridgedAllOf
            //Assert.IsInstanceOf(typeof(ScheduleRulesetAbridgedAllOf), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'DaySchedules'
        /// </summary>
        [Test]
        public void DaySchedulesTest()
        {
            // TODO unit test for the property 'DaySchedules'
        }
        /// <summary>
        /// Test the property 'DefaultDaySchedule'
        /// </summary>
        [Test]
        public void DefaultDayScheduleTest()
        {
            // TODO unit test for the property 'DefaultDaySchedule'
        }
        /// <summary>
        /// Test the property 'ScheduleRules'
        /// </summary>
        [Test]
        public void ScheduleRulesTest()
        {
            // TODO unit test for the property 'ScheduleRules'
        }
        /// <summary>
        /// Test the property 'HolidaySchedule'
        /// </summary>
        [Test]
        public void HolidayScheduleTest()
        {
            // TODO unit test for the property 'HolidaySchedule'
        }
        /// <summary>
        /// Test the property 'SummerDesigndaySchedule'
        /// </summary>
        [Test]
        public void SummerDesigndayScheduleTest()
        {
            // TODO unit test for the property 'SummerDesigndaySchedule'
        }
        /// <summary>
        /// Test the property 'WinterDesigndaySchedule'
        /// </summary>
        [Test]
        public void WinterDesigndayScheduleTest()
        {
            // TODO unit test for the property 'WinterDesigndaySchedule'
        }
        /// <summary>
        /// Test the property 'ScheduleTypeLimit'
        /// </summary>
        [Test]
        public void ScheduleTypeLimitTest()
        {
            // TODO unit test for the property 'ScheduleTypeLimit'
        }

    }

}
