/* 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HoneybeeSchema;

using System.Reflection;
using Newtonsoft.Json;

namespace HoneybeeSchema.Test
{
    /// <summary>
    ///  Class for testing ScheduleTypeLimitAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduleTypeLimitAllOfTests
    {
        // TODO uncomment below to declare an instance variable for ScheduleTypeLimitAllOf
        //private ScheduleTypeLimitAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScheduleTypeLimitAllOf
            //instance = new ScheduleTypeLimitAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScheduleTypeLimitAllOf
        /// </summary>
        [Test]
        public void ScheduleTypeLimitAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ScheduleTypeLimitAllOf
            //Assert.IsInstanceOf(typeof(ScheduleTypeLimitAllOf), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'LowerLimit'
        /// </summary>
        [Test]
        public void LowerLimitTest()
        {
            // TODO unit test for the property 'LowerLimit'
        }
        /// <summary>
        /// Test the property 'UpperLimit'
        /// </summary>
        [Test]
        public void UpperLimitTest()
        {
            // TODO unit test for the property 'UpperLimit'
        }
        /// <summary>
        /// Test the property 'NumericType'
        /// </summary>
        [Test]
        public void NumericTypeTest()
        {
            // TODO unit test for the property 'NumericType'
        }
        /// <summary>
        /// Test the property 'UnitType'
        /// </summary>
        [Test]
        public void UnitTypeTest()
        {
            // TODO unit test for the property 'UnitType'
        }

    }

}
