/* 
 * Honeybee Model Schema
 *
 * Documentation for Honeybee model schema
 *
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace HoneybeeSchema
{
    /// <summary>
    /// An enumeration.
    /// </summary>
    /// <value>An enumeration.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum EvaporativeCoolerEquipmentType
    {
        /// <summary>
        /// Enum Baseboardelectric for value: Direct evap coolers with baseboard electric
        /// </summary>
        [EnumMember(Value = "Direct evap coolers with baseboard electric")]
        Direct evap coolers with baseboard electric = 1,

        /// <summary>
        /// Enum Baseboardgasboiler for value: Direct evap coolers with baseboard gas boiler
        /// </summary>
        [EnumMember(Value = "Direct evap coolers with baseboard gas boiler")]
        Direct evap coolers with baseboard gas boiler = 2,

        /// <summary>
        /// Enum Baseboardcentralairsourceheatpump for value: Direct evap coolers with baseboard central air source heat pump
        /// </summary>
        [EnumMember(Value = "Direct evap coolers with baseboard central air source heat pump")]
        Direct evap coolers with baseboard central air source heat pump = 3,

        /// <summary>
        /// Enum Baseboarddistricthotwater for value: Direct evap coolers with baseboard district hot water
        /// </summary>
        [EnumMember(Value = "Direct evap coolers with baseboard district hot water")]
        Direct evap coolers with baseboard district hot water = 4,

        /// <summary>
        /// Enum Forcedairfurnace for value: Direct evap coolers with forced air furnace
        /// </summary>
        [EnumMember(Value = "Direct evap coolers with forced air furnace")]
        Direct evap coolers with forced air furnace = 5,

        /// <summary>
        /// Enum Gasunitheaters for value: Direct evap coolers with gas unit heaters
        /// </summary>
        [EnumMember(Value = "Direct evap coolers with gas unit heaters")]
        Direct evap coolers with gas unit heaters = 6,

        /// <summary>
        /// Enum Noheat for value: Direct evap coolers with no heat
        /// </summary>
        [EnumMember(Value = "Direct evap coolers with no heat")]
        Direct evap coolers with no heat = 7

    }

}
