/* 
 * Honeybee Model Schema
 *
 * Documentation for Honeybee model schema
 *
 * Contact: info@ladybug.tools
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

extern alias LBTNewtonSoft; using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using LBTNewtonSoft::Newtonsoft.Json;
using LBTNewtonSoft::Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;


namespace HoneybeeSchema
{
    /// <summary>
    /// A single character for the view type (-vt).
    /// </summary>
    /// <value>A single character for the view type (-vt).</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ViewType
    {
        /// <summary>
        /// Enum V for value: v
        /// </summary>
        [EnumMember(Value = "v")]
        v = 1,

        /// <summary>
        /// Enum H for value: h
        /// </summary>
        [EnumMember(Value = "h")]
        h = 2,

        /// <summary>
        /// Enum L for value: l
        /// </summary>
        [EnumMember(Value = "l")]
        l = 3,

        /// <summary>
        /// Enum C for value: c
        /// </summary>
        [EnumMember(Value = "c")]
        c = 4,

        /// <summary>
        /// Enum A for value: a
        /// </summary>
        [EnumMember(Value = "a")]
        a = 5,

        /// <summary>
        /// Enum S for value: s
        /// </summary>
        [EnumMember(Value = "s")]
        s = 6

    }

}
