version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_name: "honeybee-schema"
          update_type: "all"
    commit_message:
      prefix: "honeybee_schema_release"
      include_scope: true
