//This is auto generated by create_interface.py
//Do not edit this manually!.
namespace HoneybeeSchema.Radiance
{
	public partial interface IState {}
}

//Classes implemented this interface:
namespace HoneybeeSchema
{
	public partial class RadianceShadeStateAbridged: HoneybeeSchema.Radiance.IState {}
	public partial class RadianceSubFaceStateAbridged: HoneybeeSchema.Radiance.IState {}
	public partial class StateGeometryAbridged: HoneybeeSchema.Radiance.IState {}
}
