name: CI-On-Dispatch

on: repository_dispatch

jobs:
  bump_honeybee_schema:
    name: "Bump honeybee_schema"
    runs-on: ubuntu-latest
    if: github.event.action == 'honeybee_schema_release'
    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v4
        with:
          ref: refs/heads/master
          token: ${{ secrets.DEPS_UPDATING }}
          submodules: recursive

      - name: "Update version in requirements.txt"
        env:
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          export CLEAN_VERSION=$(echo $VERSION | sed 's/v//g')
          sed -i --regexp-extended 's/(honeybee-schema==).*/honeybee-schema=='"$CLEAN_VERSION"'/' requirements.txt

      - name: "Run SchemaGenerator"
        run: |
          cd ./.generator/SchemaGenerator
          dotnet run --download --genCsModel --genCsInterface --genTsModel --updateVersion

      - name: "Run build"
        run: |
          cd ./src/HoneybeeSchema
          dotnet build

      - name: "Commit and Push Changes"
        id: push
        env:
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          git config --global user.name 'ladybugbot'
          git config --global user.email 'ladybugbot@users.noreply.github.com'
          git add .
          git commit -m "fix(deps): Bump honeybee-schema openapi doc to $VERSION"
          git push
