name: NPM release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - src/TypeScriptSDK/**
      - .github/workflows/npm_package.yml

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      CI: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: generate files
        run: |
          cd ./.nswag-generator
          dotnet run --genTsModel --updateVersion

      - name: Install dependencies
        working-directory: src/TypeScriptSDK
        run: npm i

      - name: Build module
        working-directory: src/TypeScriptSDK
        run: npm run build

      - name: Publish to npm
        working-directory: src/TypeScriptSDK
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
