name: NPM release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - src/TypeScriptSDK/**

jobs:
  release:
    name: release
    if: github.repository_owner == 'pollination'
    runs-on: ubuntu-latest
    env:
      CI: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: make module-install

      - name: Build module
        run: make module-prod

      - name: Install semantic-release
        run: npm install -g semantic-release@18.0.0

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: ladybugbot
          GIT_AUTHOR_EMAIL: ${{ secrets.POLLINATION_LADYBUGBOT_EMAIL }}
          GIT_COMMITTER_NAME: ladybugbot
          GIT_COMMITTER_EMAIL: ${{ secrets.POLLINATION_LADYBUGBOT_EMAIL }}
        run: make NPM-publish
