name: NPM release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - src/TypeScriptSDK/**
      - .github/workflows/npm_package.yml

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      CI: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: generate files
        run: |
          node -v

      - name: Install dependencies
        working-directory: src/TypeScriptSDK
        run: |
          npm cache clean --force
          npm install
          npm ls

      - name: Build module
        working-directory: src/TypeScriptSDK
        run: npm run build
