name: CI

on: repository_dispatch

jobs:
  updateImage:
    name: "Check Event"
    runs-on: ubuntu-latest
    if: github.event.action == 'honeybee_schema_release'

    steps:
    - name: "Checkout Master Branch"
      uses: actions/checkout@v2
      with:
        ref: refs/heads/master
        token: ${{ secrets.GH_TOKEN }}


    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64

    - name: "Install OpenAPI-generator"
      run: |
        npm install @openapitools/openapi-generator-cli@cli-4.3.0
      
    - name: "Run Update Script"
      env:
        VERSION: ${{ github.event.client_payload.version }}
      run: |
        python3 .openapi-generator/download_schema.py $VERSION
        python3 .openapi-generator/generate.py $VERSION

    - name: "Commit and Push Changes"
      id: push
      env:
        VERSION: ${{ github.event.client_payload.version }}
        COMMIT_MESSAGE: ${{ steps.vars.outputs.commit_message }}
      run: |
        git config --global user.name 'ladybugbot'
        git config --global user.email 'ladybugbot@users.noreply.github.com'
        git add .
        git commit -m "feat(schema): Update Schema to $VERSION"
        git push